name: CI-CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  IMAGE_TAG: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push image
        if: github.event_name != 'pull_request'
        run: docker push $IMAGE_NAME:$IMAGE_TAG

  deploy-with-terraform:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -upgrade -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        env:
          TF_VAR_image_name: ${{ env.IMAGE_NAME }}
          TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
          TF_VAR_container_name: hello-world-app
          TF_VAR_container_port: 3000
          TF_VAR_host_port: 3000
        run: terraform apply -auto-approve -input=false